version: '3.4'
services:
  app:
    build: ./app
    env_file:
      - ./app/.env
    environment:
      - PUBLIC_API_ORIGIN_NODE=http://host.docker.internal:3001
    ports:
      - "3000:3000"
  api:
    build: ./api
    env_file:
      - ./api/.env
    environment:
      - DATABASE_URL=file:/usr/src/app/data/dev.db
    ports:
      - "3001:3001"
    volumes:
      - ./data:/usr/src/app/data
