version: "3.4"
services:
  app:
    build: ./app
    env_file:
      - ./app/.env
    environment:
      - PUBLIC_API_ORIGIN_NODE=${PUBLIC_API_ORIGIN_NODE}
    ports:
      - "3000:3000"
  api:
    build: ./api
    env_file:
      - ./api/.env
    environment:
      - PGHOST=${PGHOST}
    ports:
      - "3001:3001"
  postgres:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    image: postgres
    ports:
      - "5432:5432"
